services:
  api-gateway:
    build: utilities-payment-api-gateway/
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
    depends_on:
      - auth
      - billing
      - payment
      - cache
    ports:
      - 8080:8080
    container_name: gateway
    networks:    
      - backend

  cache:
    image: memcached:alpine
    ports:
      - 11211:11211
    container_name: cache
    networks:    
      - backend
    restart: always

  auth:
    build: utilities-payment-auth/
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
    ports:
      - 44044:44044
    container_name: auth
    networks:    
      - backend

  billing-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    container_name: billing-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:    
      - backend
    volumes:
      - billing-db:/var/lib/postgresql/

  billing:
    build: utilities-payment-billing/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CONFIG_PATH: ./config/dev.yaml
    depends_on:
      billing-db:
        condition: service_healthy
    ports:
      - 44080:44080
    container_name: billing
    networks:    
      - backend

  payment:
    build: utilities-payment-payment/
    ports:
      - 44000:44000
    container_name: payment
    networks:    
      - backend

  frontend:
    build: utilities-payment-frontend/
    ports:
      - 5500:80
    container_name: frontend
    networks:    
      - frontend

volumes:
  billing-db:

networks:
  backend:
  frontend: