host: "gateway" # Имя хоста должно совпадать с названием сервиса в docker-compose файле
port: 8080
secret: "AUTH-SECRET-AUTH" # Секрет должен совпадать с таковым в сервисе Auth
timeout: 5s
auth:
  host: "auth"
  port: 44044 # Порты так же должны совпадать с таковыми в docker-compose файле для каждого сервиса
billing:
  host: "billing"
  port: 44080
payment:
  host: "payment"
  port: 44000