name: 'Tests'

on: ["push"]

jobs:
  tests:
    name: 'Run tests'
    runs-on: ubuntu-latest
    env:
      AUTH_SECRET: TEST-SECRET

    steps:
      - uses: actions/checkout@v5

      - name: Fetch submodules
        run: |
          git submodule init
          git submodule update

      - name: Build the stack
        run: docker compose -f docker-compose.test.yml up -d --build

      - name: Setup Go 1.25.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Install dependencies
        working-directory: ./utilities-payment-api-gateway
        run: |        
          go mod tidy
          go mod verify
          go mod download

      - name: Run tests
        working-directory: ./utilities-payment-api-gateway
        run: go test -v ./tests
